check-leaks: true
file:
  - './test/es/CoreObject-test.js'
  - './test/es/MetaObject-test.js'
  - './test/es/mixins/StateMachineMixin-test.js'
  - './test/es/statemachine/Event-test.js'
full-trace: true
growl: true
recursive: false
reporter: 'spec'
require: '@babel/register'
