check-leaks: true
color: true
extension:
  - 'js'
file:
  - './test/es/CoreObject-test.js'
  - './test/es/MetaObject-test.js'
  - './test/es/mixins/StateMachineMixin-test.js'
  - './test/es/statemachine/Event-test.js'
  - './test/es/statemachine/State-test.js'
  - './test/es/statemachine/StateMachine-test.js'
  - './test/es/statemachine/Transition-test.js'
  - './test/es/utils/filter-test.js'
  - './test/es/utils/forEach-test.js'
  - './test/es/utils/jsonStringify-test.js'
  - './test/es/utils/map-test.js'
  - './test/puremvc/command/Command-test.js'
  - './test/puremvc/facade/Facade-test.js'
  - './test/puremvc/core/Controller-test.js'
  - './test/puremvc/core/Model-test.js'
  - './test/puremvc/core/View-test.js'
  - './test/puremvc/mediator/Mediator-test.js'
  - './test/puremvc/proxy/Proxy-test.js'
  - './test/puremvc/observer/Notification-test.js'
  - './test/puremvc/observer/Notifier-test.js'
  - './test/puremvc/observer/Observer-test.js'
  - './test/pipes/Filter-test.js'
  - './test/pipes/FilterControlMessage-test.js'
  - './test/pipes/Junction-test.js'
  - './test/pipes/JunctionMediator-test.js'
  - './test/pipes/LineControlMessage-test.js'
  - './test/pipes/Line-test.js'
  - './test/pipes/LogFilterMessage-test.js'
  - './test/pipes/LogMessage-test.js'
  - './test/pipes/Pipe-test.js'
  - './test/pipes/PipeAwareModule-test.js'
  - './test/pipes/PipeListener-test.js'
  - './test/pipes/PipeMessage-test.js'
  - './test/pipes/TeeMerge-test.js'
  - './test/pipes/TeeSplit-test.js'
  - './test/leanes/facade/Application-test.js'
  - './test/leanes/mixins/LoggingJunctionMixin-test.js'
  - './test/leanes/command/LogMessageCommand-test.js'
  - './test/leanes/command/Script-test.js'
  - './test/es/decorators/method-test.js'
  - './test/es/decorators/property-test.js'
  - './test/es/decorators/util-test.js'
  - './test/es/decorators/nameBy-test.js'
  - './test/es/decorators/machine-test.js'
  - './test/es/decorators/mixin-test.js'
  - './test/es/decorators/decorator-test.js'
  - './test/es/decorators/partOf-test.js'
  - './test/es/decorators/resolver-test.js'
  - './test/es/decorators/initializeMixin-test.js'
  - './test/es/decorators/meta-test.js'
  - './test/es/decorators/initialize-test.js'
  - './test/es/decorators/constant-test.js'
  - './test/es/decorators/chains-test.js'
  - './test/es/decorators/freeze-test.js'
full-trace: true
growl: true
recursive: false
reporter: 'spec'
require: '@babel/register'
# spec: 'test/**/**/*-test.js'
watch: true
