check-leaks: true
file:
  # - './test/es/CoreObject-test.js'
  # - './test/es/MetaObject-test.js'
  # - './test/es/mixins/StateMachineMixin-test.js'
  # - './test/es/statemachine/Event-test.js'
  # - './test/es/statemachine/State-test.js'
  # - './test/es/statemachine/StateMachine-test.js'
  # - './test/es/statemachine/Transition-test.js'
  # - './test/es/utils/filter-test.js'
  # - './test/es/utils/forEach-test.js'
  # - './test/es/utils/jsonStringify-test.js'
  # - './test/es/utils/map-test.js'
  # - './test/leanes/data_mapper/ArrayTransform-test.js'
  # - './test/leanes/data_mapper/BooleanTransform-test.js'
  # - './test/leanes/data_mapper/DateTransform-test.js'
  # - './test/leanes/data_mapper/NumberTransform-test.js'
  # - './test/leanes/data_mapper/Objectizer-test.js'
  # - './test/leanes/data_mapper/ObjectTransform-test.js'
  # - './test/leanes/data_mapper/StringTransform-test.js'
  # - './test/leanes/data_mapper/Transform-test.js'
  # - './test/patternes/command/SimpleCommand-test.js'
  # - './test/patternes/command/MacroCommand-test.js'
  # - './test/patternes/facade/Facade-test.js'
  # - './test/leanes/facade/Application-test.js'
  # - './test/patternes/core/Controller-test.js'
  # - './test/patternes/core/Model-test.js'
  - './test/patternes/core/View-test.js'
full-trace: true
growl: true
recursive: false
reporter: 'spec'
require: '@babel/register'
